### ISSUE TITLE
[Encoding] Set-PSMDCmdletBinding converts to UTF8 rather than UTF8-BOM

### ISSUE THREAD

**Issue by Clebam** [PowershellFrameworkCollective/PSUtil#35]
I don't know if it is rather a problem from this command or from the Get-FileEncoding function

```
function Get-FileEncoding
{
<#
	.SYNOPSIS
		Tests a file for encoding.
	
	.DESCRIPTION
		Tests a file for encoding.
	
	.PARAMETER Path
		The file to test
#>
	[CmdletBinding()]
	Param (
		[Parameter(Mandatory = $True, ValueFromPipelineByPropertyName = $True)]
		[Alias('FullName')]
		[string]
		$Path
	)
	
	[byte[]]$byte = get-content -Encoding byte -ReadCount 4 -TotalCount 4 -Path $Path
	
	if ($byte[0] -eq 0xef -and $byte[1] -eq 0xbb -and $byte[2] -eq 0xbf) { 'UTF8' }
	elseif ($byte[0] -eq 0xfe -and $byte[1] -eq 0xff) { 'Unicode' }
	elseif ($byte[0] -eq 0 -and $byte[1] -eq 0 -and $byte[2] -eq 0xfe -and $byte[3] -eq 0xff) { 'UTF32' }
	elseif ($byte[0] -eq 0x2b -and $byte[1] -eq 0x2f -and $byte[2] -eq 0x76) { 'UTF7' }
	else { 'Unknown, possible ASCII' }
}

Get-FileEncoding C:\UTF8File.ps1 ==> Unknown, possible ASCII
Get-FileEncoding C:\UTF8-BOMFile.ps1 ==> UTF8
```

**Comment by FriedrichWeinmann** [comment]
Actually, that's "working as designed" (But the design needs some reconsideration)
Basically, all `Get-FileEncoding` really does is check for BOM entries. So it detects UTF8 only if it has BOM.
One of those cases of "But it's so obvious" developer tunnel vision things. Should have updated the returned strings and updated the validation to be explicit about the BOM requirement.
Why `Set-PSMDCmdletBinding` is misbehaving in this instance is ... troubling, should have considered that more fully earlier.

**Comment by Clebam** [comment]
I narrowed the problem down to this:
[System.IO.File]::WriteAllText($key, $newString)

Obviously, this method writes by default in UTF8 (Without BOM):
Remarks
This method uses UTF-8 encoding without a Byte-Order Mark (BOM) ==> https://docs.microsoft.com/en-us/dotnet/api/system.io.file.writealltext?redirectedfrom=MSDN&view=netframework-4.7.2#System_IO_File_WriteAllText_System_String_System_String_

The method accepts an overload for encoding but the thing is I don't know if you can get the current encoding with certainty :-/

**Comment by FriedrichWeinmann** [comment]
Yeah, that's the bandit, for sure. It's the root of all encoding evil in PSModuleDevelopment:
It writes in the default encoding for the given locale, not the one the text originally was in and not what would be technically sane.
Going to change that behavior - in fact, I will have to revisit a lot of commands in that module in order to make things right.

**Comment by FriedrichWeinmann** [comment]
Fixed by now, totally forgot this orphaned issue, sorry
