### ISSUE TITLE
Set-PSUPathAlias and Register-PSUPathAlias

### ISSUE THREAD

**Issue by AndrewPla** [PowershellFrameworkCollective/PSUtil#37]
Add 2 new commands to enable using aliases to navigate the filesystem.

## Usage

```powershell
# Registers an alias for Set-PSUPathAlias named 'temp' and sets the value of the path
Register-PSUPathAlias -Name 'work' -Path 'C:\work'

# We can now call Set-PSUPathAlias by the 'work' alias and it will set our location to C:\work
work`
```

## Set-PSUPathAlias

- This command is intended to be called by an alias that you have defined with Register-PSUPathAlias
- Changes the current location of the console
- Detects the name of the alias that calls it and sets it to the associated path

## Register-PSUPathAlias

- Uses Set-PSFConfig and Register-PSFConfig and Set-Alias.
- Has a parameter that allows you to register the setting (register-psfconfig)
- Default behavior will just use Set-PSFConfig

## Other Changes

The fullname that we will be using for config system settings is psutil.pathalias.$alias
We will need to add some code the the scripts that get run upon module import that will go through 

```powershell
get-psfconfig -fullname psutil.pathalias.* | foreach {Get-PSFConfigValue -fullname $_.fullname}
```

**Comment by FriedrichWeinmann** [comment]
Closed as implemented.
Thank you again for all the hard work on this :)
