### ISSUE TITLE
to get notification for a new release please publish it in github too

### ISSUE THREAD

**Issue by mi-hol** [PowershellFrameworkCollective/PSUtil#46]
To stay on top of new release the new feature 'watch release' was introduced on github recently.
To get notified of a new release please publish them in github too

**Comment by FriedrichWeinmann** [comment]
Heya, sorry about the late response, I'll see to it for future releases on my repositories

**Comment by FriedrichWeinmann** [comment]
Alright, got updates to github as release working :)
